# namePrefix: dev-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: joy-k8s

images:
- name: yuchiao/zlh
  newTag: '1'

labels:
  - pairs:
      env: rel
      project: dt
      team: dt
    includeTemplates: true

resources:
  - superstar.yml

## // ------------------------------------------------------------------- // ##
## * env * ##
#secretGenerator:
#- name: superstar.json
#  namespace: joy-k8s
#  files:
#  - envConfig=env/superstar.json
#  options:
#    disableNameSuffixHash: true
#    labels:
#      app: superstar
## // ------------------------------------------------------------------- // ##
